rajonai_su_gatvem = {
    'Antakalnis': ['A. Kojelavičiaus g.',
                   'Antakalnio g.',
                   'Balžio g.',
                   'Bistryčios g.',
                   'Filaretų g.',
                   'Gailestingųjų Seserų g.',
                   'K. Semenavičiaus g.',
                   'Kalno g.',
                   'Kanklių g.',
                   'Karių Kapų g.',
                   'Klinikų g.',
                   'Kučkuriškių g.',
                   'L. Sapiegos g.',
                   'Lentupio g.',
                   'M. K. Oginskio g.',
                   'M. K. Paco g.',
                   'M. Počobuto g.',
                   'Nemenčinės pl.',
                   'Nugalėtojų g.',
                   'Olandų g.',
                   'P. Vileišio g.',
                   'Peteliškių g.',
                   'Petro Rimšos g.',
                   'Pylimėlių g.',
                   'Rato g.',
                   'Rudens g.',
                   'Saulenių g.',
                   'Saulės g.',
                   'Saulėtekio al.',
                   'Smėlio g.',
                   'Svajonių g.',
                   'T. Kosciuškos g.',
                   'Tramvajų g.',
                   'Turniškių g.',
                   'Tverečiaus g.',
                   'V. Grybo g.',
                   'Volungės g.',
                   'Vytauto Žalakevičiaus g.',
                   'Šilo g.',
                   'Švyturio g.',
                   'Žirgo g.',
                   'Žolyno g.'],
    'Aukštieji Paneriai': ['Juodšilių g.', 'Šešėlių g.'],
    'Avižieniai': ['Mokyklos g.', 'Saulės g.', 'Sodų g.'],
    'Bajorai': ['Bajorų kel.',
                'Fizikų g.',
                'Jono Kairiūkščio g.',
                'Mokslininkų g.',
                'Mokyklos g.',
                'Mykolo Marcinkevičiaus g.'],
    'Balsiai': ['Popieriaus g.', 'Verkių Riešės g.', 'Žaliųjų Ežerų g.'],
    'Baltupiai': ['Ateities g.',
                  'Baltupio g.',
                  'Didlaukio g.',
                  'Kalvarijų g.',
                  'Kareivių g.',
                  'Mokyklos g.',
                  'Naujakiemio g.',
                  'Trinapolio g.',
                  'Visorių g.',
                  'Žirmūnų g.'],
    'Bukiškio k.': ['Mokyklos g.'],
    'Burbiškės': ['Burbiškių g.', 'Eišiškių pl.'],
    'Dvarčionys': ['Keramikų g.'],
    'Fabijoniškės': ['Ateities g.',
                     'Fabijoniškių g.',
                     'Gedvydžių g.',
                     'L. Giros g.',
                     'P. Žadeikos g.',
                     'S. Stanevičiaus g.',
                     'Salomėjos Nėries g.',
                     'Ukmergės g.'],
    'Filaretai': ['Filaretų g.', 'Olandų g.', 'Rudens g.'],
    'Grigiškės': ['Saulės g.',
                  'Savanorių pr.',
                  'Vilniaus g.',
                  'Šviesos g.',
                  'Žalioji g.'],
    'Jeruzalė': ['Ateities g.',
                 'Baltupio g.',
                 'Bitininkų g.',
                 'Braškių g.',
                 'Didlaukio g.',
                 'Kalvarijų Sodų 5-oji g.',
                 'Kalvarijų g.',
                 'Mokyklos g.',
                 'Mykolo Marcinkevičiaus g.',
                 'Rugių g.',
                 'Visorių g.'],
    'Justiniškės': ['Justiniškių g.',
                    'Laisvės pr.',
                    'Mozūriškių g.',
                    'Rygos g.',
                    'Taikos g.',
                    'Talino g.'],
    'Kalnėnai': ['Gurių g.'],
    'Karoliniškės': ['Algimanto Petro Kavoliuko g.',
                     'Igno Šimulionio g.',
                     'Laisvės pr.',
                     'Loretos Asanavičiūtės g.',
                     'Miškinių g.',
                     'Sausio 13-osios g.',
                     'Sietyno g.',
                     'Virginijaus Druskio g.'],
    'Lazdynai': ['Architektų g.',
                 'Erfurto g.',
                 'Jonažolių g.',
                 'Lazdynėlių g.',
                 'Lazdynų g.',
                 'M. Mironaitės g.',
                 'Miškinių g.',
                 'Šiltnamių g.',
                 'Žėručio g.'],
    'Lazdynėliai': ['Bukčių g.',
                    'Jonažolių g.',
                    'Lazdynėlių g.',
                    'Miškinių g.',
                    'Neužmirštuolių g.',
                    'Rūko g.',
                    'Šiltnamių g.'],
    'Lentvario m.': ['Saulės g.'],
    'Liepkalnis': ['Liepkalnio g.', 'Miškinių g.', 'Perlojos g.'],
    'Markučiai': ['Filaretų g.',
                  'Markučių g.',
                  'Paplaujos g.',
                  'Paupio g.',
                  'Sibiro g.',
                  'Subačiaus g.'],
    'Naujamiestis': ['A. Goštauto g.',
                     'A. Jakšto g.',
                     'A. Rotundo g.',
                     'A. Smetonos g.',
                     'A. Vivulskio g.',
                     'Aguonų g.',
                     'Algirdo g.',
                     'Aludarių g.',
                     'Antano Tumėno g.',
                     'Birželio 23-iosios g.',
                     'Brolių g.',
                     'Dariaus ir Girėno g.',
                     'Eglių g.',
                     'Eišiškių pl.',
                     'Gedimino pr.',
                     'Geležinio Vilko g.',
                     'Gerosios Vilties g.',
                     'Iešmininkų g.',
                     'J. Basanavičiaus g.',
                     'J. Jasinskio g.',
                     'Jogailos g.',
                     'K. Donelaičio g.',
                     'Kapsų g.',
                     'Kauno g.',
                     'Konstitucijos pr.',
                     'M. K. Čiurlionio g.',
                     'M. Valančiaus g.',
                     'Mindaugo g.',
                     'Muitinės g.',
                     'Naugarduko g.',
                     'Pakalnės g.',
                     'Pamėnkalnio g.',
                     'Panerių g.',
                     'Pelesos g.',
                     'Raugyklos g.',
                     'S. Konarskio g.',
                     'Savanorių pr.',
                     'Skroblų g.',
                     'Smolensko g.',
                     'Statybininkų g.',
                     'T. Ševčenkos g.',
                     'V. Mykolaičio-Putino g.',
                     'V. Pietario g.',
                     'Vandentiekio g.',
                     'Vilkpėdės g.',
                     'Vilniaus g.',
                     'Vinco Kudirkos g.',
                     'Vytenio g.',
                     'Z. Sierakausko g.',
                     'Šaltinių g.',
                     'Šv. Stepono g.',
                     'Švitrigailos g.',
                     'Žemaitės g.'],
    'Naujininkai': ['A. Jaroševičiaus g.',
                    'Algirdo g.',
                    'Brolių g.',
                    'Burbiškių g.',
                    'Darbininkų g.',
                    'Dariaus ir Girėno g.',
                    'Dzūkų g.',
                    'Eišiškių pl.',
                    'Gudų g.',
                    'Kaminkelio g.',
                    'Kapsų g.',
                    'Konduktorių g.',
                    'Liepkalnio g.',
                    'Miškinių g.',
                    'Naugarduko g.',
                    'Panevėžio g.',
                    'Pelesos g.',
                    'Prūsų g.',
                    'Pumpurų g.',
                    'Rudaminos g.',
                    'Zanavykų g.',
                    'Šaltkalvių g.',
                    'Šv. Stepono g.'],
    'Naujoji Vilnia': ['A. Kojelavičiaus g.',
                       'A. Paškevič-Ciotkos g.',
                       'Darželio g.',
                       'Genių g.',
                       'Gerovės g.',
                       'Gluosnių g.',
                       'Kalno g.',
                       'Karklėnų g.',
                       'Linksmoji g.',
                       'Parko g.',
                       'Pavilnionių g.',
                       'Pergalės g.',
                       'Pramonės g.',
                       'Saulenių g.',
                       'Skardžio g.',
                       'Stepono Batoro g.',
                       'Žaliakalnio g.'],
    'Paneriai': ['Eišiškių pl.', 'Juodšilių g.', 'Liudvinavo g.'],
    'Pavilnys': ['Džiaugsmo g.', 'Plytų g.', 'Tuputiškių g.', 'Vandens g.'],
    'Pašilaičiai': ['Dociškių g.',
                    'Eitminų g.',
                    'Gabijos g.',
                    'Girulių g.',
                    'Jurgio Baltrušaičio g.',
                    'Justiniškių g.',
                    'Laisvės pr.',
                    'Medeinos g.',
                    'Pavilnionių g.',
                    'Pašilaičių g.',
                    'Perkūnkiemio g.',
                    'Sviliškių g.',
                    'Ukmergės g.',
                    'Virbeliškių g.',
                    'Č. Sugiharos g.',
                    'Žemynos g.'],
    'Pilaitė': ['Bitėnų g.',
                'Gilužio g.',
                'I. Kanto al.',
                'I. Simonaitytės g.',
                'Juodkrantės g.',
                'Karaliaučiaus g.',
                'M. Mažvydo g.',
                'M. Pretorijaus g.',
                'Nidos g.',
                'Pajautos g.',
                'Papilėnų g.',
                'Piliakalnio g.',
                'Priegliaus g.',
                'Tolminkiemio g.',
                'Trakėnų g.',
                'Vydūno g.',
                'Įsruties g.'],
    'Rasos': ['Dzūkų g.',
              'Liepkalnio g.',
              'Naujininkų g.',
              'Olandų g.',
              'Rasų g.',
              'Ribiškių Didžioji g.',
              'Stadiono g.',
              'Subačiaus g.'],
    'Salininkai': ['Kalviškių g.', 'Pupinės g.', 'Salininkų g.', 'Vaikų g.'],
    'Santariškės': ['Bajorų kel.',
                    'J. Franko g.',
                    'Mykolo Marcinkevičiaus g.',
                    'Santariškių g.',
                    'Žaliųjų Ežerų g.'],
    'Saulėtekis': ['Plytinės g.', 'Pylimėlių g.'],
    'Senamiestis': ['A. Goštauto g.',
                    'A. Jakšto g.',
                    'A. Rotundo g.',
                    'A. Smetonos g.',
                    'A. Strazdelio g.',
                    'A. Stulginskio g.',
                    'A. Vienuolio g.',
                    'A. Vivulskio g.',
                    'Aguonų g.',
                    'Algirdo g.',
                    'Aludarių g.',
                    'Ankštoji g.',
                    'Antano Tumėno g.',
                    'Aukų g.',
                    'Aušros Vartų g.',
                    'Baltasis skg.',
                    'Barboros Radvilaitės g.',
                    'Bazilijonų g.',
                    'Bernardinų g.',
                    'Didžioji g.',
                    'Dominikonų g.',
                    'Dysnos g.',
                    'Etmonų g.',
                    'Filaretų g.',
                    'Gaono g.',
                    'Gedimino pr.',
                    'Gynėjų g.',
                    'Gėlių g.',
                    'Islandijos g.',
                    'J. Basanavičiaus g.',
                    'J. Jasinskio g.',
                    'J. Savickio g.',
                    'Jogailos g.',
                    'K. Kalinausko g.',
                    'Kauno g.',
                    'Kaštonų g.',
                    'Klaipėdos g.',
                    'Konstitucijos pr.',
                    'Krivių g.',
                    'Krivūlės g.',
                    'L. Stuokos-Gucevičiaus g.',
                    'Liejyklos g.',
                    'Liepkalnio g.',
                    'Ligoninės g.',
                    'Literatų g.',
                    'Lvovo g.',
                    'M. Antokolskio g.',
                    'M. Daukšos g.',
                    'M. K. Čiurlionio g.',
                    'M. Valančiaus g.',
                    'Malūnų g.',
                    'Markučių g.',
                    'Mindaugo g.',
                    'Naugarduko g.',
                    'Odminių g.',
                    'Olimpiečių g.',
                    'Pakalnės g.',
                    'Pamėnkalnio g.',
                    'Paupio g.',
                    'Pelesos g.',
                    'Pilies g.',
                    'Plačioji g.',
                    'Polocko g.',
                    'Pranciškonų g.',
                    'Pylimo g.',
                    'Raugyklos g.',
                    'Rūdninkų g.',
                    'S. Skapo g.',
                    'Savanorių pr.',
                    'Savičiaus g.',
                    'Sodų g.',
                    'Stiklių g.',
                    'Subačiaus g.',
                    'Suvalkų g.',
                    'T. Kosciuškos g.',
                    'T. Vrublevskio g.',
                    'T. Ševčenkos g.',
                    'Teatro g.',
                    'Tilto g.',
                    'Totorių g.',
                    'Trakų g.',
                    'Universiteto g.',
                    'Užupio g.',
                    'V. Mykolaičio-Putino g.',
                    'V. Šopeno g.',
                    'Vasario 16-osios g.',
                    'Vilniaus g.',
                    'Vingrių g.',
                    'Vokiečių g.',
                    'Šaltinių g.',
                    'Šermukšnių g.',
                    'Šiaulių g.',
                    'Šv. Ignoto g.',
                    'Šv. Jono g.',
                    'Šv. Kazimiero g.',
                    'Šv. Mykolo g.',
                    'Šv. Stepono g.',
                    'Švitrigailos g.',
                    'Žemaitijos g.',
                    'Žygimantų g.'],
    'Trakų Vokė': ['J. Tiškevičiaus g.'],
    'Turniškės': ['Nemenčinės pl.', 'Turniškių g.'],
    'Užupis': ['Baltasis skg.',
               'Darbo g.',
               'Filaretų g.',
               'Kreivasis skg.',
               'Krivių g.',
               'Krivūlės g.',
               'Maironio g.',
               'Malūnų g.',
               'Markučių g.',
               'Olandų g.',
               'Paplaujos g.',
               'Paupio g.',
               'Peteliškių g.',
               'Polocko g.',
               'Subačiaus g.',
               'Užupio g.',
               'Šv. Kazimiero g.'],
    'Valakampiai': ['Balžio g.',
                    'Lizdeikos g.',
                    'Nemenčinės pl.',
                    'Nugalėtojų g.',
                    'Rato g.',
                    'Svajonių g.',
                    'Turniškių g.'],
    'Verkiai': ['Kalvarijų g.',
                'Popieriaus g.',
                'Trinapolio g.',
                'Verkių g.',
                'Žaliųjų Ežerų g.'],
    'Vilkpėdė': ['Burbiškių g.',
                 'Gerosios Vilties g.',
                 'Miškinių g.',
                 'Savanorių pr.',
                 'Vaduvos g.',
                 'Vilkpėdės g.'],
    'Viršuliškės': ['Buivydiškių g.',
                    'Viršilų g.',
                    'Viršuliškių g.',
                    'Šešuolių g.'],
    'Visoriai': ['Ateities g.',
                 'Bajorų kel.',
                 'Jono Kairiūkščio g.',
                 'Visorių g.'],
    'Šeškinė': ['Buivydiškių g.',
                'Deltuvos g.',
                'Dūkštų g.',
                'Gelvonų g.',
                'Laisvės pr.',
                'Musninkų g.',
                'Ozo g.',
                'Paberžės g.',
                'Siesikų g.',
                'Ukmergės g.',
                'Čiobiškio g.',
                'Šeškinės g.'],
    'Šiaurės miestelis': ['Kareivių g.',
                          'S. Žukausko g.',
                          'Ulonų g.',
                          'Žirmūnų g.',
                          'Žygio g.'],
    'Šnipiškės': ['A. Juozapavičiaus g.',
                  'Apkasų g.',
                  'Daugėliškio g.',
                  'Durpių g.',
                  'Giedraičių g.',
                  'Kalvarijų g.',
                  'Kareivių g.',
                  'Kernavės g.',
                  'Kintų g.',
                  'Konstitucijos pr.',
                  'Krokuvos g.',
                  'Linkmenų g.',
                  'Lvovo g.',
                  'Naujakiemio g.',
                  'Olimpiečių g.',
                  'Rinktinės g.',
                  'Saracėnų g.',
                  'Tuskulėnų g.',
                  'Šeimyniškių g.',
                  'Šilutės g.',
                  'Širvintų g.',
                  'Žalgirio g.'],
    'Žemieji Paneriai': ['Savanorių pr.', 'Vaduvos g.'],
    'Žirmūnai': ['Apkasų g.',
                 'Kalvarijų g.',
                 'Kareivių g.',
                 'Kernavės g.',
                 'Konstitucijos pr.',
                 'M. Katkaus g.',
                 'Minties g.',
                 'Olimpiečių g.',
                 'Raitininkų g.',
                 'Rinktinės g.',
                 'S. Žukausko g.',
                 'Sporto g.',
                 'Trinapolio g.',
                 'Tuskulėnų g.',
                 'Ulonų g.',
                 'Verkių g.',
                 'Šeimyniškių g.',
                 'Žirmūnų g.',
                 'Žygio g.'],
    'Žvėrynas': ['A. Mickevičiaus g.',
                 'Antano Tumėno g.',
                 'Birutės g.',
                 'Blindžių g.',
                 'Danielių g.',
                 'Elnių g.',
                 'Kęstučio g.',
                 'Lapų g.',
                 'Latgalių g.',
                 'Latvių g.',
                 'Liepyno g.',
                 'Liubarto g.',
                 'Lokių g.',
                 'Lūšių g.',
                 'Malonioji g.',
                 'Miglos g.',
                 'Paribio g.',
                 'Pušų g.',
                 'S. Moniuškos g.',
                 'Sakalų g.',
                 'Saltoniškių g.',
                 'Sausio 13-osios g.',
                 'Stirnų g.',
                 'Stumbrų g.',
                 'Sėlių g.',
                 'Treniotos g.',
                 'Vykinto g.',
                 'Vytauto g.']
}


uzklausos_pvz1 = {
    "rajonas": "Antakalnis",
    "gatve": "Bistryčios g.",
    "kambariai": 3,
    "plotas": 54,
    "aukstas": 4,
    "aukstu": 12
}

uzklausos_pvz2 = {
    "rajonas": "Senamiestis",
    "gatve": "A. Goštauto g.",
    "kambariai": 2,
    "plotas": 44,
    "aukstas": 3,
    "aukstu": 5
}

uzklausos_pvz3 = {
    "rajonas": "Naujininkai",
    "gatve": "Burbiškių g.",
    "kambariai": 1,
    "plotas": 30,
    "aukstas": 5,
    "aukstu": 12
}
